# Generated by Django 5.1.7 on 2025-03-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("topic", models.CharField(max_length=120)),
                ("number_of_questions", models.IntegerField()),
                ("time", models.IntegerField(help_text="thời lượng")),
                (
                    "required_score_to_pass",
                    models.IntegerField(help_text="điểm cần để qua"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Hiểu biết", "Hiểu biết"),
                            ("Vận dụng", "Vận dụng"),
                            ("Vận dụng cao", "Vận dụng cao"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]