# Generated by Django 5.1.7 on 2025-03-26 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizes"},
        ),
    ]