# Generated by Django 5.2 on 2025-04-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0002_alter_quiz_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="required_score_to_pass",
            field=models.FloatField(help_text="Điểm cần để qua"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="time",
            field=models.IntegerField(help_text="Thời lượng làm bài (phút)"),
        ),
    ]
